all:
	moc LayoutWindow.h -o LayoutWindow.moc
	g++ -o a.out LayoutWindow.cpp -I/usr/include/qt4/QtGui/ -I/usr/include/qt4/Qt/ -I/usr/include/qt4/ -L/usr/lib/x86_64-linux-gnu -lQtGui -lQtCore -lpthread
